import React from "react";
import { motion } from "framer-motion";
import { fadeInUp, staggerContainer } from "./about";
import styles from "./education.module.scss";

export default function Education() {
  return (
    <div className={styles.page}>
      <div className={styles.container}>
        <motion.section
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, margin: "-100px" }}
          variants={staggerContainer}
          className={styles.sectionGrid}
        >
          <div className={styles.sectionText}>
            <motion.h2 variants={fadeInUp} className={styles.sectionTitleAccent}>
              What is Deconstruction?
            </motion.h2>
            <motion.p variants={fadeInUp}>
              Deconstruction is the systematic dismantling of a building in order to maximize the recovery of materials for reuse and recycling. Unlike traditional demolition, which relies on heavy machinery to quickly crush a structure and haul the debris to a landfill, deconstruction is a careful, labor-intensive process that treats a building as a repository of valuable resources.
            </motion.p>
          </div>
          <motion.div variants={fadeInUp} className={styles.imageWrapper}>
            <img
              src="/src/assets/images/lumber_co.jpg"
              alt="Reclaimed wood planks in a workshop"
              className={styles.sectionImage}
              onError={(e) => {
                e.currentTarget.src = 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?q=80&w=2000&auto=format&fit=crop';
              }}
            />
          </motion.div>
        </motion.section>

        <motion.section
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, margin: "-100px" }}
          variants={staggerContainer}
          className={styles.sectionGrid}
        >
          <motion.div variants={fadeInUp} className={styles.imageWrapperLeft}>
            <img
              src="/src/assets/images/education-2.png"
              alt="Worker cooperative members gathered"
              className={styles.sectionImage}
              onError={(e) => {
                e.currentTarget.src = 'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?q=80&w=2000&auto=format&fit=crop';
              }}
            />
          </motion.div>
          <div className={styles.sectionTextRight}>
            <motion.h2 variants={fadeInUp} className={styles.sectionTitlePrimary}>
              What is a Worker-Owned Cooperative?
            </motion.h2>
            <motion.p variants={fadeInUp}>
              A worker-owned cooperative is a business that is owned and democratically governed by its employees. Instead of external shareholders or a single owner extracting profits, the wealth generated by the company is shared equitably among the people doing the actual work.
            </motion.p>
          </div>
        </motion.section>
      </div>
    </div>
  );
}
