import React from "react";
import { motion } from "framer-motion";
import { fadeInUp, staggerContainer } from "./about";

export default function Education() {
  return (
    <div className="flex-1 bg-[#F8F7F5] py-16 sm:py-24">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-5xl space-y-24">
        
        {/* Section 1: What is Deconstruction? */}
        <motion.section 
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, margin: "-100px" }}
          variants={staggerContainer}
          className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center"
        >
          <div className="order-2 lg:order-1 space-y-6 text-[#515048] font-light leading-relaxed">
            <motion.h2 variants={fadeInUp} className="text-3xl md:text-4xl font-bold text-[#C97023] mb-8">
              What is Deconstruction?
            </motion.h2>
            <motion.p variants={fadeInUp}>
              Deconstruction is the systematic dismantling of a building in order to maximize the recovery of materials for reuse and recycling. Unlike traditional demolition, which relies on heavy machinery to quickly crush a structure and haul the debris to a landfill, deconstruction is a careful, labor-intensive process that treats a building as a repository of valuable resources.
            </motion.p>
          </div>
          <motion.div variants={fadeInUp} className="order-1 lg:order-2 rounded-lg overflow-hidden shadow-xl">
            <img 
              src="/src/assets/images/education-1.png" 
              alt="Reclaimed wood planks in a workshop" 
              className="w-full h-[400px] object-cover"
              onError={(e) => {
                e.currentTarget.src = 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?q=80&w=2000&auto=format&fit=crop';
              }}
            />
          </motion.div>
        </motion.section>

        {/* Section 2: What is a Worker-Owned Cooperative? */}
        <motion.section 
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, margin: "-100px" }}
          variants={staggerContainer}
          className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center"
        >
          <motion.div variants={fadeInUp} className="rounded-lg overflow-hidden shadow-xl">
            <img 
              src="/src/assets/images/education-2.png" 
              alt="Worker cooperative members gathered" 
              className="w-full h-[400px] object-cover"
              onError={(e) => {
                e.currentTarget.src = 'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?q=80&w=2000&auto=format&fit=crop';
              }}
            />
          </motion.div>
          <div className="space-y-6 text-[#515048] font-light leading-relaxed">
            <motion.h2 variants={fadeInUp} className="text-3xl md:text-4xl font-bold text-[#456C1B] mb-8">
              What is a Worker-Owned Cooperative?
            </motion.h2>
            <motion.p variants={fadeInUp}>
              A worker-owned cooperative is a business that is owned and democratically governed by its employees. Instead of external shareholders or a single owner extracting profits, the wealth generated by the company is shared equitably among the people doing the actual work.
            </motion.p>
           
          </div>
        </motion.section>

      </div>
    </div>
  );
}
