import React from "react";
import { motion } from "framer-motion";
import {
  ClipboardList,
  Wrench,
  Package,
  Leaf,
  Vote,
  DollarSign,
  Eye,
  Shield,
  TrendingUp,
  Users,
  Sprout,
} from "lucide-react";
import { fadeInUp, staggerContainer } from "./about";
import lumberCoImg from "../assets/images/lumber_co.jpg";
import styles from "./education.module.scss";

type StepColor = "accent" | "primary";
type PrincipleColor = "accent" | "primary";
type PillarColor = "accent" | "primary" | "text";

const timelineSteps = [
  {
    icon: ClipboardList,
    number: "01",
    title: "Assessment & Planning",
    body: "We evaluate the building leveraging technology to identify salvageable materials and create a strategic dismantling plan.",
    color: "accent" as StepColor,
  },
  {
    icon: Wrench,
    number: "02",
    title: "Careful Dismantling",
    body: "Using hand tools and efficient techniques, we systematically remove materials, preserving their integrity and character.",
    color: "primary" as StepColor,
  },
  {
    icon: Package,
    number: "03",
    title: "Material Sorting & Processing",
    body: "Each salvageable piece is carefully sorted, and prepared for reuse or resale.",
    color: "accent" as StepColor,
  },
  {
    icon: Leaf,
    number: "04",
    title: "Value Reclamation",
    body: "We make quality lumber, architectural elements, and building components available for new projects, extending their life indefinitely. Buying reclaimed materials is also an important way to support our mission.",
    color: "primary" as StepColor,
  },
];

function stepColorClass(color: StepColor) {
  return color === "accent" ? styles.stepAccent : styles.stepPrimary;
}

function labelColorClass(color: StepColor) {
  return color === "accent" ? styles.labelAccent : styles.labelPrimary;
}

function principleCardClass(color: PrincipleColor) {
  return color === "accent" ? styles.principleCardAccent : styles.principleCardPrimary;
}

function principleIconClass(color: PrincipleColor) {
  return color === "accent" ? styles.principleIconAccent : styles.principleIconPrimary;
}

function benefitHeaderClass(color: PillarColor) {
  if (color === "accent") return styles.benefitHeaderEconomic;
  if (color === "primary") return styles.benefitHeaderSocial;
  return styles.benefitHeaderEnvironmental;
}

function benefitBulletClass(color: PillarColor) {
  if (color === "accent") return styles.benefitBulletAccent;
  if (color === "primary") return styles.benefitBulletPrimary;
  return styles.benefitBulletText;
}

const principles = [
  {
    icon: Vote,
    title: "Democratic Governance",
    body: "One member, one vote ensures that every employee-owner has equal say in business decisions, regardless of their position or financial investment. This creates a truly democratic workplace where power is distributed rather than concentrated.",
    color: "accent" as PrincipleColor,
  },
  {
    icon: DollarSign,
    title: "Economic Equity",
    body: "Workers share in the profits generated by their labor, creating a more equitable distribution of wealth within the business. Compensation structures often prioritize fairness and living wages while maintaining reasonable differentials for specialized skills or responsibilities.",
    color: "primary" as PrincipleColor,
  },
  {
    icon: Eye,
    title: "Accountability and Transparency",
    body: "Because employees are owners, there's built-in accountability to the workforce rather than distant shareholders. Financial information, strategic decisions, and company performance are typically shared openly among all members.",
    color: "accent" as PrincipleColor,
  },
  {
    icon: Shield,
    title: "Job Security and Stability",
    body: "Worker cooperatives tend to prioritize long-term sustainability over short-term profits, leading to greater job stability and security for employees. The commitment to worker welfare reduces turnover and builds institutional knowledge.",
    color: "primary" as PrincipleColor,
  },
];

const benefitPillars = [
  {
    icon: TrendingUp,
    title: "Economic",
    color: "accent" as PillarColor,
    points: [
      "Larger in scale than many traditional small businesses",
      "More resilient during economic downturns due to their focus on long-term stability rather than quarterly profits",
      "Equally or more productive than their non-cooperative counterparts, demonstrating that democratic governance doesn't come at the cost of efficiency",
    ],
  },
  {
    icon: Users,
    title: "Social",
    color: "primary" as PillarColor,
    points: [
      "Reduced income inequality through more equitable distribution of profits",
      "Stronger local economies by keeping wealth within communities",
      "Empowered workers who have control over their working conditions and futures",
      "Greater job satisfaction and higher employee engagement",
    ],
  },
  {
    icon: Sprout,
    title: "Environmental",
    color: "text" as PillarColor,
    points: [
      "Employee-owners have a direct stake in the long-term health of their communities and workplaces",
      "The democratic structure makes it easier to implement environmentally responsible decisions",
      "Sustainable practices are built into company culture and values",
    ],
  },
];

const CorePrinciples = () => (
  <motion.div
    initial="hidden"
    whileInView="visible"
    viewport={{ once: true, margin: "-80px" }}
    variants={staggerContainer}
    className={styles.principlesInfographic}
  >
    <motion.div variants={fadeInUp} className={styles.infographicHeader}>
      <span className={styles.infographicEyebrow}>What Makes Co-ops Different</span>
      <h3 className={styles.infographicTitle}>The 4 Core Principles of Worker Co-ops</h3>
      <div className={styles.infographicTitleBar} />
    </motion.div>

    <div className={styles.principlesGrid}>
      {principles.map((principle, i) => {
        const Icon = principle.icon;
        return (
          <motion.div
            key={principle.title}
            variants={fadeInUp}
            custom={i}
            className={`${styles.principleCard} ${principleCardClass(principle.color)}`}
          >
            <div className={`${styles.principleIcon} ${principleIconClass(principle.color)}`}>
              <Icon className={styles.principleIconSvg} strokeWidth={1.5} />
            </div>
            <div>
              <h4 className={styles.principleTitle}>{principle.title}</h4>
              <p className={styles.principleBody}>{principle.body}</p>
            </div>
          </motion.div>
        );
      })}
    </div>
  </motion.div>
);

const BenefitsPillars = () => (
  <motion.div
    initial="hidden"
    whileInView="visible"
    viewport={{ once: true, margin: "-80px" }}
    variants={staggerContainer}
    className={styles.benefitsInfographic}
  >
    <motion.div variants={fadeInUp} className={styles.infographicHeader}>
      <span className={styles.infographicEyebrow}>Why It Works</span>
      <h3 className={styles.infographicTitle}>The Benefits of the Cooperative Model</h3>
      <div className={`${styles.infographicTitleBar} ${styles.infographicTitleBarPrimary}`} />
    </motion.div>

    <div className={styles.benefitsGrid}>
      {benefitPillars.map((pillar, i) => {
        const Icon = pillar.icon;
        return (
          <motion.div
            key={pillar.title}
            variants={fadeInUp}
            custom={i}
            className={styles.benefitCard}
          >
            <div className={`${styles.benefitHeader} ${benefitHeaderClass(pillar.color)}`}>
              <div className={styles.benefitHeaderIcon}>
                <Icon className={styles.benefitHeaderIconSvg} strokeWidth={1.5} />
              </div>
              <h4 className={styles.benefitHeaderTitle}>{pillar.title}</h4>
              <p className={styles.benefitHeaderSubtitle}>Advantages</p>
            </div>
            <div className={styles.benefitPoints}>
              {pillar.points.map((point) => (
                <div key={point} className={styles.benefitPoint}>
                  <div className={`${styles.benefitBullet} ${benefitBulletClass(pillar.color)}`} />
                  <p className={styles.benefitPointText}>{point}</p>
                </div>
              ))}
            </div>
          </motion.div>
        );
      })}
    </div>
  </motion.div>
);

const TimelineInfographic = () => {
  return (
    <motion.div
      initial="hidden"
      whileInView="visible"
      viewport={{ once: true, margin: "-80px" }}
      variants={staggerContainer}
      className={styles.timeline}
    >
      <motion.div variants={fadeInUp} className={styles.infographicHeader}>
        <span className={styles.infographicEyebrow}>How It Works</span>
        <h3 className={styles.infographicTitle}>The Rica Deconstruction Process</h3>
        <div className={styles.infographicTitleBar} />
      </motion.div>

      <div className={styles.timelineDesktop}>
        <div className={styles.timelineConnector} />

        <div className={styles.timelineGrid}>
          {timelineSteps.map((step, i) => {
            const Icon = step.icon;
            return (
              <motion.div
                key={step.number}
                variants={fadeInUp}
                custom={i}
                className={styles.timelineStep}
              >
                <div className={`${styles.timelineStepIcon} ${stepColorClass(step.color)}`}>
                  <Icon className={styles.timelineStepIconSvg} strokeWidth={1.5} />
                  <span className={styles.timelineStepBadge}>
                    {step.number}
                  </span>
                </div>
                <h4 className={styles.timelineStepTitle}>{step.title}</h4>
                <p className={styles.timelineStepBody}>{step.body}</p>
              </motion.div>
            );
          })}
        </div>
      </div>

      <div className={styles.timelineMobile}>
        <div className={styles.timelineVerticalLine} />

        <div className={styles.timelineMobileList}>
          {timelineSteps.map((step, i) => {
            const Icon = step.icon;
            return (
              <motion.div
                key={step.number}
                variants={fadeInUp}
                custom={i}
                className={styles.timelineMobileStep}
              >
                <div className={`${styles.timelineMobileDot} ${stepColorClass(step.color)}`}>
                  <Icon className={styles.timelineMobileDotSvg} strokeWidth={1.5} />
                </div>
                <div className={styles.timelineMobileContent}>
                  <div className={`${styles.timelineMobileLabel} ${labelColorClass(step.color)}`}>
                    Step {step.number}
                  </div>
                  <h4 className={styles.timelineMobileTitle}>{step.title}</h4>
                  <p className={styles.timelineMobileBody}>{step.body}</p>
                </div>
              </motion.div>
            );
          })}
        </div>
      </div>
    </motion.div>
  );
};

export default function Education() {
  return (
    <div className={styles.page}>
      <div className={styles.container}>
        <motion.section
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, margin: "-100px" }}
          variants={staggerContainer}
          className={styles.deconstructionSection}
        >
          <motion.section
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, margin: "-100px" }}
            variants={staggerContainer}
            className={styles.introSection}
          >
            <motion.h2 variants={fadeInUp} className={styles.sectionTitleAccent}>
              What is Deconstruction?
            </motion.h2>
            <motion.p variants={fadeInUp}>
              Deconstruction is the thoughtful, methodical process of carefully dismantling buildings to salvage and reuse as many materials as possible, rather than demolishing them and sending everything to landfills. It's a building practice that sees structures not as disposable, but as repositories of value, history, and possibility.
            </motion.p>
          </motion.section>

          <motion.section
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, margin: "-100px" }}
            variants={staggerContainer}
            className={styles.differsGrid}
          >
            <div className={styles.differsText}>
              <motion.h3 variants={fadeInUp} className={styles.sectionSubheading}>
                How Deconstruction Differs
                <br />
                from Demolition
              </motion.h3>
              <motion.p variants={fadeInUp}>
                Demolition is typically a fast, brute-force process designed to clear space quickly. Heavy machinery tears down structures, crushing materials meaning they end up in landfills. While efficient for immediate clearance, it results in massive waste and lost resources.
              </motion.p>
              <motion.p variants={fadeInUp}>
                Deconstruction, on the other hand, is a craft-driven process that values every component. Our skilled team carefully disassembles buildings piece by piece, preserving materials like lumber, windows, doors, fixtures, and architectural elements that can be given new life. It's slower and more labor-intensive, but the environmental and community benefits are profound. In addition, with effective technology-enabled processes and lack of machinery rental, the cost differences can be minimal.
              </motion.p>
            </div>
            <motion.div variants={fadeInUp} className={styles.differsImageWrapper}>
              <img
                src={lumberCoImg}
                alt="Reclaimed wood planks in a workshop"
                className={styles.sectionImage}
                onError={(e) => {
                  e.currentTarget.src = 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?q=80&w=2000&auto=format&fit=crop';
                }}
              />
            </motion.div>
          </motion.section>

          <div className={styles.sectionTextFull}>
            <TimelineInfographic />

            <motion.h3 variants={fadeInUp} className={styles.sectionSubheading}>
              Why Choose Deconstruction?
            </motion.h3>
            <motion.p variants={fadeInUp}>
              <strong>Environmental Impact:</strong> Deconstruction diverts 80-90% of building materials from landfills, reducing waste and carbon emissions associated with new material production.
            </motion.p>
            <motion.p variants={fadeInUp}>
              <strong>Economic Benefits:</strong> Salvaged materials are often more affordable than new ones, making sustainable building more accessible. We also create dignified, shared-ownership jobs in the process.
            </motion.p>
            <motion.p variants={fadeInUp}>
              <strong>Historical Preservation:</strong> Many older buildings contain irreplaceable materials - old-growth lumber, unique hardware, and architectural details that simply can't be replicated today.
            </motion.p>
            <motion.p variants={fadeInUp}>
              <strong>Community Building:</strong> By reusing local materials, we strengthen community connections and reduce the cost and environmental impact of transporting new materials from distant sources.
            </motion.p>

            <motion.h3 variants={fadeInUp} className={styles.sectionSubheading}>
              The Circular Construction Economy
            </motion.h3>
            <motion.p variants={fadeInUp}>
              Deconstruction is a cornerstone of the circular construction economy - where materials move locally, workers share ownership, and communities build more equitable and beautiful places using what already exists. Instead of the "take-make-waste" linear model, we create a system where materials are valued, preserved, and reused for generations.
            </motion.p>
            <motion.p variants={fadeInUp}>
              At Rica Lumber and Deconstruction, we're not just taking buildings apart. We're revealing the value already embedded in our built environment and showing that sustainable construction can be both beautiful and practical.
            </motion.p>
          </div>
        </motion.section>

        <motion.section
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, margin: "-100px" }}
          variants={staggerContainer}
          className={styles.cooperativeSection}
        >
          <motion.section
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, margin: "-100px" }}
            variants={staggerContainer}
            className={styles.introSection}
          >
            <motion.h2 variants={fadeInUp} className={styles.sectionTitleAccent}>
              What is a Worker-Owned Cooperative?
            </motion.h2>
            <motion.p variants={fadeInUp}>
              A cooperative is a business that is owned and democratically controlled by its employees. Unlike traditional corporations where ownership is concentrated among shareholders who may not be involved in daily operations, cooperatives place ownership directly in the hands of the people who do the work. Each employee becomes an owner with both a financial stake in the company and equal voting rights in major company decisions.
            </motion.p>
            <motion.p variants={fadeInUp}>
              This fundamental difference creates a business model where workers are not just cogs in a machine, but partners in enterprise. Employees collectively own and govern their workplace, aligning their interests with the long-term success and sustainability of the organization.
            </motion.p>
          </motion.section>

          <CorePrinciples />

          <motion.section
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, margin: "-100px" }}
            variants={staggerContainer}
            className={styles.introSection}
          >
            <motion.p variants={fadeInUp}>
              Worker-owned cooperatives represent more than just a different way to organize a business—they offer a vision for a more democratic, equitable, and sustainable economy built on the principle that those who do the work should share in the rewards.
            </motion.p>
          </motion.section>

          <div className={styles.sectionTextFull}>
            <BenefitsPillars />
          </div>
        </motion.section>
      </div>
    </div>
  );
}
